version: '3.8'

services:
  flatnotes:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flatnotes-prod
    ports:
      - "3001:3001"
    volumes:
      # 数据持久化 - 重要：确保数据不丢失
      - ./data:/app/data:rw
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 认证密码 - 生产环境，强烈建议修改为强密码
      - AUTH_PASSWORD=${AUTH_PASSWORD:-flatnotes222}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"